export const IOC = {
  WINDOW: Symbol.for("WINDOW"),
  LOGGER: Symbol.for("LOGGER"),
  TRANSLATOR: Symbol.for("TRANSLATOR"),
  STATE_MANAGER: Symbol.for("STATE_MANAGER"),
  RUNNER: Symbol.for("RUNNER"),
  LOGGER_LINK: Symbol.for("LOGGER_LINK"),
  EXECUTOR_LINK: Symbol.for("EXECUTOR_LINK"),
  TASK_REPOSITORY: Symbol.for("TASK_REPOSITORY"),
  GET_TASKS_QUERY: Symbol.for("GET_TASKS_QUERY"),
  CREATE_TASK_COMMAND: Symbol.for("CREATE_TASK_COMMAND"),
  CHANGE_STATUS_TASK_COMMAND: Symbol.for("CHANGE_STATUS_TASK_COMMAND"),
  REMOVE_TASK_COMMAND: Symbol.for("REMOVE_TASK_COMMAND"),
};
