export const IOC = {
  USE_CASE_DECORATOR: Symbol.for("USE_CASE_DECORATOR"),
  LOGGER: Symbol.for("LOGGER"),
  WINDOW: Symbol.for("WINDOW"),
  STATE_MANAGER: Symbol.for("STATE_MANAGER"),
  RUNNER: Symbol.for("RUNNER"),
  LOGGER_LINK: Symbol.for("LOGGER_LINK"),
  EXECUTOR_LINK: Symbol.for("EXECUTOR_LINK"),
  TASK_REPOSITORY: Symbol.for("TASK_REPOSITORY"),
  GET_TASKS_QUERY: Symbol.for("GET_TASKS_QUERY"),
  CREATE_TASK_COMMAND: Symbol.for("CREATE_TASK_COMMAND"),
  COMPLETE_TASK_COMMAND: Symbol.for("COMPLETE_TASK_COMMAND"),
};
